FROM openjdk:8-jdk-alpine
COPY target/*SNAPSHOT.jar app.jar
EXPOSE 8080

############################ JENNIFER SETTING START #########################
#####################
###   수정 필요   ###
#####################
ARG CONF_FILE_NM=order   # 제니퍼 대쉬보드에 표시할 업무 이름 (각 MSA별로 다르게 지정)
ARG DOMAIN_ID_DEV=2021
ARG DOMAIN_ID_PRD=2036
ARG DOMAIN_ID_ETC=2236

#####################
###   Don't Touch ###
#####################
ARG PRD_STRING=dev
ARG DEV_STRING=C.UTF-8
ARG J_SERVER_IP=10.0.2.15
ARG AGENT_VERSION=5.5.3
ARG JENNIFER_HOME=/opt
ARG AGENT_HOME=$JENNIFER_HOME/agent.java
COPY jennifer-agent-java-$AGENT_VERSION.zip /
RUN unzip -oq jennifer-agent-java-${AGENT_VERSION}.zip -d /$JENNIFER_HOME
RUN RUNNING_MODE=`echo $LANG` && \
    if [ $RUNNING_MODE = $PRD_STRING ]; then RUNNING_MODE=$DOMAIN_ID_PRD; \
    elif [ $RUNNING_MODE = $DEV_STRING ] ; then RUNNING_MODE=$DOMAIN_ID_DEV; \
    else RUNNING_MODE=$DOMAIN_ID_ETC; fi && \
    value=`cat $AGENT_HOME/conf/jennifer.conf` && \
    echo "${value//domain_id = 1000/domain_id = $RUNNING_MODE}" >| $AGENT_HOME/conf/$CONF_FILE_NM.conf
RUN value=`cat $AGENT_HOME/conf/$CONF_FILE_NM.conf` && echo "${value//192.168.0.1/$J_SERVER_IP}" >| $AGENT_HOME/conf/$CONF_FILE_NM.conf
#####################
############################ JENNIFER SETTING END #########################

#ENTRYPOINT cat /opt/agent.java/conf/order.conf | grep domain_id
ENTRYPOINT ["java","-Xmx400M","-javaagent:/opt/agent.java/jennifer.jar","-Djennifer.config=/opt/agent.java/conf/order.conf","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar","--spring.profiles.active=default"]
