server:
  port: 8080
---

spring:
  profiles: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1588-pizza?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: admin
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      # ddl-auto: update
      ddl-auto: create
      generate-ddl: true
  cloud:
    stream:
      kafka:
        binder:
#          brokers: 10.0.2.15:9092
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: customercenter
          destination: pizza
          contentType: application/json
        event-out:
          destination: pizza
          contentType: application/json

logging:
  level:
    root: info
    org.hibernate.type: trace
    org.hibernate.type.BasicTypeRegistry: WARN
    org.springframework.cloud: info
    org.apache.kafka.common.utils.AppInfoParser: WARN
    org.apache.kafka.clients.Metadata: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    org.hibernate.hql.internal.QueryTranslatorFactoryInitiator: WARN

server:
  port: 8084
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: customercenter
          destination: pizza
          contentType: application/json
        event-out:
          destination: pizza
          contentType: application/json
